//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Gosol.CMS.Web.Webapp.Frontend
{


    public partial class LoaiTinTucDetailDemo
    {

        /// <summary>
        /// lblTenLoaiTin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTenLoaiTin;

        /// <summary>
        /// rptLoaiTinTuc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptLoaiTinTuc;

        /// <summary>
        /// plhPaging control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder plhPaging;

        /// <summary>
        /// SideBarDanhMucTinTuc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Com.Gosol.CMS.Web.Webapp.Frontend.SideBar2 SideBarDanhMucTinTuc;
    }
}
